name: e2e Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: e2e Test Stage
    runs-on: ubuntu-latest
    environment: e2e

    env:
        WORKING_DIRECTORY: . 
        GLUON_API_KEY: ${{ secrets.GLUON_API_KEY }}

    steps:
      - uses: actions/checkout@main

      - name: Install Packages
        run: npm i
        
      - name: Install gluon-cli
        run: npm i -g @jhenrycode/gluon-cli
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Ensure 5 iPhones on 17.2 are Provisioned
        run: gluon-cli ensure-capacity 17-4 iPhone-15 2
    
      - name: Ensure 2 iPads on 17.5 are Provisioned
        run: gluon-cli ensure-capacity 17-4 iPad-Pro-13-inch-M4-8GB 1
    
      - name: Run iPhone tests
        run: ./scripts/run-iphone-tests.sh

      - name: Run iPad tests
        run: ./scripts/run-ipad-tests.sh
